### ISSUE TITLE
option to download each page as an image file?

### ISSUE THREAD

**Issue by newbiegituserj** [elementdavv/internet_archive_downloader#1]
Really cool extension man! Is there an option to save the pages individually as images file instead of all pages together in PDF? Again wonderful extension!

**Comment by elementdavv** [comment]
You can use release v0.1.0 which downloads every page as a jpeg. Read the correspondant README file for the usage.

**Comment by newbiegituserj** [comment]
I'm not very good at computers but I'll try, thank you!

**Comment by elementdavv** [comment]
1. download https://github.com/elementdavv/internet_archive_downloader/releases/download/v0.1.0/iadownloader-0.1.0.zip
2. extract iadownloader-0.1.0.zip somewhere.
3. open extension manager in browser(chrome://extensions or edge://extensions), enable developer mode. Find and click a button named "load unpacked" or similar name, in the popup dialog select the previous extracted folder.
4. Install another extension named "Allow CORS: Access-Control-Allow-Origin". In its option page, enable "Access-Control-Allow-Credentials".
5. That's all. Now you can download books in every page.

**Comment by newbiegituserj** [comment]
thank you!
