### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by CluelessCoder69** [elementdavv/internet_archive_downloader#10]
I downloaded the extension. I went to the internet archive, and the buttons were not there. What happened? I don't see it. Am I doing something wrong? Am I missing something? Pls help.

**Comment by elementdavv** [comment]
You need to borrow the book.

**Comment by CluelessCoder69** [comment]
Tried it. It worked. Thanks.

**Comment by CluelessCoder69** [comment]
I tried it, and it worked. Thanks.
