### ISSUE TITLE
ReferenceError: showSaveFilePicker is not defined

### ISSUE THREAD

**Issue by DottsGit** [elementdavv/internet_archive_downloader#11]
Windows 10 Home 22H2 19045.3208
Brave Browser [Version 1.56.11 Chromium: 115.0.5790.102 (Official Build) (64-bit)](https://brave.com/latest/)

File attempted:
https://archive.org/details/vomwortdeslebens0000adle

Attempting to download a book.  Received the error:
ReferenceError: showSaveFilePicker is not defined
Please contact the developer.

**Comment by elementdavv** [comment]
Enable 'file-system-access-api' item from 'brave://flags' page
For every launch of Brave, disable and enable the extension once
