### ISSUE TITLE
Return Borrowed Books

### ISSUE THREAD

**Issue by youperb** [elementdavv/internet_archive_downloader#13]
1. I have noticed that iadownloader v0.6.1 has been just released. I am using iadownloader v0.6.0 and It works very well . Shall I upgrade to the latest version?
2. Is there any possibility to return the borrowed books automatically after the download is completed, instead of doing so manually?

**Comment by elementdavv** [comment]
1. All users are encouraged to upgrade to 0.6.1. It prevents potential leaf losts, thought which happened rarely.
2. What do you mean by 'return the borrowed books' ?

**Comment by youperb** [comment]
Thanks a lot.
I mean to interfere programmatically and click on the red return button after the download is complete.... So the book will be available for other users.

**Comment by elementdavv** [comment]
It is a great idea. I will considerate adding the function in the next version.
