### ISSUE TITLE
File download was blocked. Please contact the developer.

### ISSUE THREAD

**Issue by drjaska** [elementdavv/internet_archive_downloader#15]
When attempting to download https://archive.org/details/introductiontogr0000trud I get the following error:

![image](https://github.com/elementdavv/internet_archive_downloader/assets/88596812/28e0a4ad-0329-4a6c-8be0-19e4bdc34a91)

I have given additional permissions here:

![image](https://github.com/elementdavv/internet_archive_downloader/assets/88596812/9896cb12-d98e-4962-aa30-7516221a8f76)

OS: Linux (Debian Testing)
Firefox 117.0 (64-bit) from Debian Unstable in private browsing.

I saw https://elementdavv.github.io/ mentioned in another issue and I get no console errors there outside of missing favicon.ico which is irrelevant.

**Comment by elementdavv** [comment]
The extension depends on some functions that doesn't work in private mode.
So do not run in private window.

**Comment by wcpot10** [comment]
Hi,
I was facing the same problem and i wasn't in private mode so I disabled "**Block cookies**" and "**Trackers & ads blocking**". Now it works. I was using Brave Browser.

**Comment by elementdavv** [comment]
> Hi, I was facing the same problem and i wasn't in private mode so I disabled "**Block cookies**" and "**Trackers & ads blocking**". Now it works. I was using Brave Browser.

Yes. If you use Brave, you can enable 'File System Access API' in 'brave://flags' page, or just disable the lion button after the addressbar.
