### ISSUE TITLE
PDF files takes 0 Bytes

### ISSUE THREAD

**Issue by youperb** [elementdavv/internet_archive_downloader#16]
Thank you for the last version.
It works perfectly with Zip Files. 
PDF files are corrupted. after the download finishes and the book is returned, the PDF files takes 0 Bytes.
I guess it is better not to return the book immediately. you should make it wait for about 30 seconds before being returned.... probably more time with old and slow computers. This will give enough time to the book to be fully compiled.

**Comment by elementdavv** [comment]
Thank you for your report. I have observed the defect.

**Comment by ffuentesm** [comment]
I am having the same problem too.
I had to go back to 6.1 to be able to get the PDFs again.

**Comment by elementdavv** [comment]
The fixed version has been released. Please upgrade it.

**Comment by youperb** [comment]
thank you vey much. I do appreciate your help.
With some books I got error 504

**Comment by ffuentesm** [comment]
I get 504 and 502 sometimes. 
For that I keep trying to download again. As it's a Network failure. 
But sometimes my download speed is so slow that the 1 hour loan expires before its fully downloaded. 
Does this extension works with the 14 day loan?

**Comment by elementdavv** [comment]
> thank you vey much. I do appreciate your help. 
> With some books I got error 504

> I get 504 and 502 sometimes. For that I keep trying to download again. As it's a Network failure. But sometimes my download speed is so slow that the 1 hour loan expires before its fully downloaded. Does this extension works with the 14 day loan?

Error 502 and 504 are network errors, just clicking 'Download' again to resume. Or try in another time of the day. The extension works with 1 hour or 14 day loan.

**Comment by youperb** [comment]
Thank you
