### ISSUE TITLE
Error 502 when trying to download PDF

### ISSUE THREAD

**Issue by ffuentesm** [elementdavv/internet_archive_downloader#17]
Hello, I am trying to download a big PDF from IA and whenever is close to completion, it fails to download. 
I am on Chrome and I updated to the 6.3 version, and I was able to download a +300MB PDF just a while ago, but this one keeps giving me an error, even after trying all other quality types to see if it was a file size issue. 
![image](https://github.com/elementdavv/internet_archive_downloader/assets/44974827/c6988bcd-e984-40a9-9ade-24c6de5183ca)
This is the file I am trying to access: https://archive.org/details/longmananthology0001unse_p9n3/page/n3/mode/2up

**Comment by elementdavv** [comment]
It is because you have too many network erors. You can always click 'Download' to resume whenever download is aborted by manual cancel or too many network errors happened.
Or try it in another time of the day. I have tested your file and succeeded with a pdf of 795MB.

**Comment by robatino** [comment]
> It is because you have too many network erors. You can always click 'Download' to resume whenever download is aborted by manual cancel or too many network errors happened. Or try it in another time of the day. I have tested your file and succeeded with a pdf of 795MB.

I tried resuming the download with the book I was trying to download in Issue #9. It always fails (when using Firefox) when the progress bar is between "a" and "d" over the word "Downloading". After it fails, if I click on "Failed" and then click on "Download" again, it doesn't resume where it left off, it starts from the beginning, so it's not possible to finish the download. Although I'm experiencing a different kind of network error than the reporter here.

**Comment by elementdavv** [comment]
> I tried resuming the download with the book I was trying to download in Issue #9. It always fails (when using Firefox) when the progress bar is between "a" and "d" over the word "Downloading". After it fails, if I click on "Failed" and then click on "Download" again, it doesn't resume where it left off, it starts from the beginning, so it's not possible to finish the download. Although I'm experiencing a different kind of network error than the reporter here.

You should continue with #9 or post a new thread.
The extension can retry when network errors occured. Your download progress is fake and can not resume certainly. In fact you do not fetch any page of the book, because a critical function does not work in your firefox environment.
