### ISSUE TITLE
Original images

### ISSUE THREAD

**Issue by logion2000** [elementdavv/internet_archive_downloader#19]
Internet Archive stores the scanned book page images which are of high resolution. I am not sure if your browse extension downloads the original images and combines them into a single PDF? Is there a way to know the place where original images are stored so that we can download them? 
Thank you very much.

**Comment by elementdavv** [comment]
The extension download the original images, when the quality selection is four stars. If you want to get the image url, press F12 and change to network tab.

**Comment by logion2000** [comment]
Is there a way to identify the storage location of the image zip files so that we can download the zip files directly? For example, below is the web address for a book page. But I guess it contains the address for the image zip file?

https://ia801404.us.archive.org/BookReader/BookReaderImages.php?zip=/32/items/introductiontost0000baum/introductiontost0000baum_jp2.zip&file=introductiontost0000baum_jp2/introductiontost0000baum_0344.jp2&id=introductiontost0000baum&scale=4&rotate=0

**Comment by elementdavv** [comment]
> Is there a way to identify the storage location of the image zip files so that we can download the zip files directly? For example, below is the web address for a book page. But I guess it contains the address for the image zip file?
> https://ia801404.us.archive.org/BookReader/BookReaderImages.php?zip=/32/items/introductiontost0000baum/introductiontost0000baum_jp2.zip&file=introductiontost0000baum_jp2/introductiontost0000baum_0344.jp2&id=introductiontost0000baum&scale=4&rotate=0

Sure. There is a zip file at https://archive.org/download/introductiontost0000baum/introductiontost0000baum_jp2.zip, as well as a pdf file there. But they are forbidden for free users.
