### ISSUE TITLE
Download fails with "page not found" when there is clearly a page there.

### ISSUE THREAD

**Issue by glowysourworm** [elementdavv/internet_archive_downloader#2]
Use Case:  Try downloading "Possibilities" by "David Graeber". It should fail at page 475 with a dialog.

**Comment by elementdavv** [comment]
i tried it. the download failed on the last page(page 476, the back cover). actually this page doesn't exists.

**Comment by glowysourworm** [comment]
Hmm, well it seems to work now. Thanks buddy! Is there any way to know how the quality adjuster should be working? I noticed you have the "paper sizes" in your code for A4, A5, etc...  If there was a faster way to adjust the PDF zoom - it would be nice because perhaps the selector could be to quickly adjust the zoom settings prior to download (?) Nice work!

**Comment by elementdavv** [comment]
i do not work with paper size. i get only what archive.org provides. most books are in three qualities, rarely in two or four.
to check effect of each quality, just use zoom in/out button. beware that the zoom levels does not correspond to qualities one to one. when zoom in, if the page displayed immediately, means that they are the same quality.

**Comment by glowysourworm** [comment]
Sure thing, I'll have to take a look. Thanks for all your work!
