### ISSUE TITLE
Empty download files

### ISSUE THREAD

**Issue by Lindelleth** [elementdavv/internet_archive_downloader#21]
Running into an issue it seems a couple others have had in the past - when the download bar shows as complete (or almost complete, it still shows as "downloading" even when the download bar is full and asks "abort?" if I click on it again), it only downloads a 0 byte PDF and a crswap file. (Have my adblocks on that page disabled; not sure what else might be going on.)

I'm running on a Mac OS 13.0 / Chrome v. 119.0.6045.159; the book in question is this one: https://archive.org/details/isbn_0329134477

(I also gave it a try on Firefox and got a "TypeError: NetworkError when attempting to fetch resource..
Please contact the developer" message.)

**Comment by elementdavv** [comment]
Have you ever downloaded a book successfully? Generally if it still shows "downloading" it is not complete and you should wait. Do not click it again while downloading unless you want to stop it.
As for Firefox(version?) error, please provide detail message by pressing F12 then changing to 'console' page.

**Comment by Lindelleth** [comment]
Apologies, I'm a bit new to this - I allowed the download to run (on Chrome) for the full hour length that the book is borrowable, and the download doesn't complete in that time (though the bar appears to reach full). I've tried a few different books (on both browsers) and run into the same errors; I've never managed to download one successfully.

The error readings from the console page on Firefox v. 119.0.1 (64-bit) are as follows (and it appears to repeat for every subsequent page until it finally hits the abort error at the end):

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ia601400.us.archive.org/BookReader/BookReaderImages.php?zip=/24/items/isbn_0329134477/isbn_0329134477_jp2.zip&file=isbn_0329134477_jp2/isbn_0329134477_0004.jp2&id=isbn_0329134477&scale=1&rotate=0. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

TypeError: NetworkError when attempting to fetch resource. [content1.js:450:21](moz-extension://8b03739b-2daf-4092-bec6-2dbb6734b516/js/content1.js)
failed [content1.js:676:17](moz-extension://8b03739b-2daf-4092-bec6-2dbb6734b516/js/content1.js)
notify browser: abort [content1.js:481:21](moz-extension://8b03739b-2daf-4092-bec6-2dbb6734b516/js/content1.js)
AbortError: The operation was aborted.


I suspect the problem is on my end but I'm not code-savvy enough to know what to do about it.

**Comment by elementdavv** [comment]
And what are the console messages on your Chrome?

**Comment by tml** [comment]
Firefox 121.0 (64-bit), MacOS M1 CPU
Created a fresh Firefox Profile with only this extension installed

Console error repeats this pattern for each page requested by the plugin:

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ia802304.us.archive.org/BookReader/BookReaderImages.php?zip=/7/items/causesofcivilwar0000unse/causesofcivilwar0000unse_jp2.zip&file=causesofcivilwar0000unse_jp2/causesofcivilwar0000unse_0157.jp2&id=causesofcivilwar0000unse&scale=1&rotate=0. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.```

https://gist.github.com/tml/00f28fec155d61c53d7bef50c2e04856 contains a HAR of a single request, with my personal cookies elided from the HAR.

**Comment by elementdavv** [comment]
> Firefox 121.0 (64-bit), MacOS M1 CPU 
> Created a fresh Firefox Profile with only this extension installed
......
> https://gist.github.com/tml/00f28fec155d61c53d7bef50c2e04856 contains a HAR of a single request, with my personal cookies elided from the HAR.

There are some people who encounter the same problem as you that the function in the extension 
does not work to get rid of the cors issue. You can try install a third party cors extension as _@Terramoto said in https://github.com/elementdavv/internet_archive_downloader/issues/9#issuecomment-1869589088_

**Comment by tml** [comment]
Thanks, I can confirm this workaround works for me.
