### ISSUE TITLE
Resume Download Following Loan Period End

### ISSUE THREAD

**Issue by rorybd** [elementdavv/internet_archive_downloader#25]
There are certain books that are too long to download within their 1 hour loan period, which causes the extension to fail partially through the download.

One workaround for this is to use a lower quality for the download. However, would it be possible for the extension to save its progress on a particular book and resume the download after the user re-borrows it?

**Comment by elementdavv** [comment]
May be "borrowing for 14 days" can be help. Or choose another release.

Due to limitation of functions to extension within browser, files in your hard disk can not be appended. So saving download progress and resuming later is impossible.

**Comment by rorybd** [comment]
Many books cannot be borrowed for 14 days, only an hour.

An alternative would be to allow for downloading a custom range of pages; that way a user could manually download the book in smaller chunks.

**Comment by elementdavv** [comment]
> An alternative would be to allow for downloading a custom range of pages; that way a user could manually download the book in smaller chunks.

Good idea. I will considerate it in the next version.

**Comment by oversky** [comment]
> > An alternative would be to allow for downloading a custom range of pages; that way a user could manually download the book in smaller chunks.
> 
> Good idea. I will considerate it in the next version.

+1. 
It would be great to have this.
