### ISSUE TITLE
Download aborting at same spot every time 

### ISSUE THREAD

**Issue by JimDop** [elementdavv/internet_archive_downloader#26]
Tried this 3 or 4 times,  get through about 270 of 340  pages  and aborts, pretty much at the same spot.    Error log  below. 

   Firefox  v 123. 

    Would be nice if you could preserve a partial download.  The file deletes itself as soon as the error happens 

 
![image](https://github.com/elementdavv/internet_archive_downloader/assets/33990696/8c94bec9-78b6-4464-95f5-08377b1dc020)

**Comment by elementdavv** [comment]
It seems the extension doesn't work in your browser. Some people encounter the same problem as you did.
Try use Chrome like browsers.

**Comment by JimDop** [comment]
It has worked in the past, and as I mentioned it downloaded over 200 pages before aborting .   Ill try in Google Chrome.
