### ISSUE TITLE
Download drops/becomes unsuccesful halfway (firefox)

### ISSUE THREAD

**Issue by shinnith** [elementdavv/internet_archive_downloader#27]
Currently on firefox and this has been an issue for me for months. Pulled up chrome, and the extension works perfectly + as intended. If having issues on your browser, try using Chrome for this extension. 

**As always, I 10000% am so grateful for this extension and thank you so much!!**

_sincerely, a broke research student with a lack of constant internet_

**Comment by shinnith** [comment]
I feel _really_ daft but to people on firefox having the same issue... turn on optional permissions and see if it fixes the download dropping issue- worked for me just now after trying that out and now the issue is fixed.

**Comment by elementdavv** [comment]
> I feel _really_ daft but to people on firefox having the same issue... turn on optional permissions and see if it fixes the download dropping issue- worked for me just now after trying that out and now the issue is fixed.

Granting optional permissions is a must.
