### ISSUE TITLE
It does nothing.

### ISSUE THREAD

**Issue by jtheletter** [elementdavv/internet_archive_downloader#3]
I added this extension to Brave for Mac v 1.50.121 and Chrome for Mac v 111.0.5563.146, and in both browsers, nothing happened. I am logged in to the Internet Archive, I have borrowed a book, I am viewing the book pages, I have refreshed the browser, I have confirmed the extension is enabled. But I see no download button between the quality button and favorite button.

**Comment by elementdavv** [comment]
does Brave and Chrome behave the same?
it is strange that quality buton shown and download button not shown.
