### ISSUE TITLE
No buttons show up

### ISSUE THREAD

**Issue by HeyItsJono** [elementdavv/internet_archive_downloader#32]
I've installed the extension on Chrome Version 122.0.6261.111 via the app store, visited a [book](https://archive.org/details/westsrespiratory0000west), borrowed it, but there are no buttons.

**Comment by elementdavv** [comment]
Try reinstall the extension, or disable all other extensions, or reinstall Chrome. And test it again.

**Comment by HeyItsJono** [comment]
Reinstalling the extension doesn't fix it, disabling other extensions doesn't fix it, and tbh "reinstall ur browser" should not be a suggested fix for the extension not working...

**Comment by elementdavv** [comment]
> I've installed the extension on Chrome Version 122.0.6261.111 via the app store, visited a [book](https://archive.org/details/westsrespiratory0000west), borrowed it, but there are no buttons.

oh, Chrome via app store? You work on andorid? It seems doesn't support extensions, how can you install the Internet Archive Downloader?

**Comment by HeyItsJono** [comment]
> > I've installed the extension on Chrome Version 122.0.6261.111 via the app store, visited a [book](https://archive.org/details/westsrespiratory0000west), borrowed it, but there are no buttons.
> 
> oh, Chrome via app store? You work on andorid? It seems doesn't support extensions, how can you install the Internet Archive Downloader?

No, I meant the [Chrome web extension Store](https://chromewebstore.google.com/). I'm on Windows.

**Comment by elementdavv** [comment]
If it still does not work, press F12 and copy the console log of your browser.

**Comment by hydranix** [comment]
Turning off my adblocker worked for me

**Comment by catfrank** [comment]
Same bug on Chrome. But it's ok on Edge.

**Comment by elementdavv** [comment]
> Same bug on Chrome. But it's ok on Edge.

Try click the extension button on toolbar to show download buttons manually.
