### ISSUE TITLE
Possible to download ebooks from InternetArchive without creating an account on InternetArchive?

### ISSUE THREAD

**Issue by AnxiousPleaseHelp** [elementdavv/internet_archive_downloader#33]
I just want to know the step by step process of saving an ebook from the InternetArchive?

Do I need to begin by creating an account on InternetArchive first?

I hope someone can help me. 😢 😢

**Comment by elementdavv** [comment]
Yes. You need to have an account first.
After creating your account, login in the account, find a book that can be borrowed, borrow it, then you will find a "Download" button below the book viewer. Click it to download the book.
