### ISSUE TITLE
Serious Problem: How to check that the ebook I downloaded is 100% identical?

### ISSUE THREAD

**Issue by AnxiousPleaseHelp** [elementdavv/internet_archive_downloader#34]
Hello,

I just tried using the Internet Archive Downloader for the first time and I think it worked!

However, I just wanted to know if there's some way for me to check that the ebook file I downloaded to my local HDD is the same ebook file that's on the archive.org website?

The file is in PDF format.

I will make a donation if someone can help me with this serious problem.

I hope someone can help me!

**Comment by elementdavv** [comment]
The downloaded PDF file is not identical to that of on website. Actually, two repeat downloaded files of one same book can hardly be identical in binary.

**Comment by AnxiousPleaseHelp** [comment]
> The downloaded PDF file is not identical to that of on website. Actually, two repeat downloaded files of one same book can hardly be identical in binary.

Thanks for your input!

I was able to download an ebook from the Archive site last week but now the download option doesn't appear?

I just updated the Chrome web browser and I'm running Windows 10 if that helps??

**Comment by AnxiousPleaseHelp** [comment]
> The downloaded PDF file is not identical to that of on website. Actually, two repeat downloaded files of one same book can hardly be identical in binary.

I've been trying to make a donation for a while now and no payment options seem to work?

I'm using this link to make the donation: https://buymeacoffee.com/timelegend

**Comment by elementdavv** [comment]
> > The downloaded PDF file is not identical to that of on website. Actually, two repeat downloaded files of one same book can hardly be identical in binary.
> 
> Thanks for your input!
> 
> I was able to download an ebook from the Archive site last week but now the download option doesn't appear?
> 
> I just updated the Chrome web browser and I'm running Windows 10 if that helps??

The extension works well with Chrome. If it isn't, please give your operation steps.

**Comment by AnxiousPleaseHelp** [comment]
> > > The downloaded PDF file is not identical to that of on website. Actually, two repeat downloaded files of one same book can hardly be identical in binary.
> > 
> > 
> > Thanks for your input!
> > I was able to download an ebook from the Archive site last week but now the download option doesn't appear?
> > I just updated the Chrome web browser and I'm running Windows 10 if that helps??
> 
> The extension works well with Chrome. If it isn't, please give your operation steps.

Hey bro, I've been trying to donate for the past 50 minutes and it just won't work... 😢 
I made a full reply here: https://github.com/elementdavv/internet_archive_downloader/issues/38#issuecomment-2169840463

Let me know your PayPal info via PM!
