### ISSUE TITLE
Can't install on Android!

### ISSUE THREAD

**Issue by MasterZebulin** [elementdavv/internet_archive_downloader#35]
Why won't it let me install on Android!? I need it on Android!

**Comment by MasterZebulin** [comment]
What's Kiwi?

**Comment by elementdavv** [comment]
> What's Kiwi?
A Chromium based browser running on Android. It can be installed from Google Play Store.

**Comment by MasterZebulin** [comment]
Okay, I got that. Anything else I need to know?
