### ISSUE TITLE
Text?

### ISSUE THREAD

**Issue by backwoodsman7** [elementdavv/internet_archive_downloader#37]
Thank you for a very useful add-on.

Would it be possible to grab the text and add it to the PDF, so it's text-searchable?

**Comment by backwoodsman7** [comment]
Is that because the text is not doable, or too difficult, or is there the possibility of adding the capability at some point?

**Comment by backwoodsman7** [comment]
Most of the books on archive.org do have the text embedded, and the text can be searched when reading them online.  And most of the PDFs that can be downloaded also have embedded text.  I was just wondering about the possibility of grabbing the text along with the images.  This add-on is a great tool even without that capability, but it would be a nice option to have.

**Comment by backwoodsman7** [comment]
(you can ignore this; I hadn't meant to close the thread, and it looks like to re-open it I need to make a new comment.)

**Comment by elementdavv** [comment]
> Most of the books on archive.org do have the text embedded, and the text can be searched when reading them online. And most of the PDFs that can be downloaded also have embedded searchable text. I was just wondering about the possibility of grabbing the text along with the images. This add-on is a great tool even without that capability, but it would be a nice option to have.

Good idea. I will consider it in the next version.
