### ISSUE TITLE
Google Chrome or Firefox or Microsoft Edge: Which gives the most reliable download?

### ISSUE THREAD

**Issue by AnxiousPleaseHelp** [elementdavv/internet_archive_downloader#38]
I really need help here!  😢 😢  😢 😢 

I'd like to know the recommended configuration that works best when downloading ebooks from archive.org?

For example, is Chrome the number one choice or is it Firefox or Edge or Brave 

I just want to know which browser extension version will give me a 100% identical ebook from archive.org?

I hope someone can help me 😢 😢 😢 😢

**Comment by AnxiousPleaseHelp** [comment]
Also, I've been trying to make a donation for a while now and no payment options seem to work?

I'm using this link to make the donation: https://buymeacoffee.com/timelegend

**Comment by elementdavv** [comment]
> I really need help here! 😢 😢 😢 😢
> 
> I'd like to know the recommended configuration that works best when downloading ebooks from archive.org?
> 
> For example, is Chrome the number one choice or is it Firefox or Edge or Brave
> 
> I just want to know which browser extension version will give me a 100% identical ebook from archive.org?
> 
> I hope someone can help me 😢 😢 😢 😢

The extension works well with Chrome. No configuration required.
Again, 100% identical PDF file is impossible.

**Comment by elementdavv** [comment]
> Also, I've been trying to make a donation for a while now and no payment options seem to work?
> 
> I'm using this link to make the donation: https://buymeacoffee.com/timelegend

Open that link. It supports credit card payment.

**Comment by AnxiousPleaseHelp** [comment]
> > Also, I've been trying to make a donation for a while now and no payment options seem to work?
> > I'm using this link to make the donation: https://buymeacoffee.com/timelegend
> 
> Open that link. It supports credit card payment.

Hey bro, I've been trying to donate for the past 50 minutes and it just won't work.

I tried using both payment methods and it just wouldn't work... I even re-entered my banking data multiple times and it didn't help.

Maybe you can send me your PayPal account via PM on here?

**I keep getting this error:**
We are unable to authenticate your payment method. Please choose a different payment method and try again.

**Comment by elementdavv** [comment]
> **I keep getting this error:** We are unable to authenticate your payment method. Please choose a different payment method and try again.

The new donation link is: [paypal](https://paypal.me/timelegend). I have updated it in README file.
