### ISSUE TITLE
ReferenceError:ShowSaveFilePicker not defined

### ISSUE THREAD

**Issue by cyris69** [elementdavv/internet_archive_downloader#4]
![image](https://user-images.githubusercontent.com/987691/234689585-70be590c-9bf3-455c-9e78-43dbdab5590f.png)

**Comment by cyris69** [comment]
using Brave  v1.50.121 windows 11

**Comment by elementdavv** [comment]
Navigate to brave://flags
In the search box type file-system-access-api
Change the File System API item's status to Enabled

**Comment by elementdavv** [comment]
Well, after change the config, it is still failed.
So Brave is not supported.
