### ISSUE TITLE
New buttons won't appear

### ISSUE THREAD

**Issue by LanceTX** [elementdavv/internet_archive_downloader#5]
Is there anything that needs to be done to activate the extension after installing it? I installed it and then borrowed a book, but the new buttons that are supposed to appear are not appearing. 
![Screenshot (5949)](https://user-images.githubusercontent.com/30740936/237059291-2a402678-2b1d-44d5-b8fc-11b59a6f9c60.png)

**Comment by elementdavv** [comment]
With v0.3.0 from chrome webstore, the buttons sometimes do not show up on low networks. You must refresh several times to make it work. Or you could try the [v0.3.2](https://github.com/elementdavv/internet_archive_downloader/releases/tag/v0.3.2) that do work on low networks.

**Comment by vehosah** [comment]
> With v0.3.0 from chrome webstore, the buttons sometimes do not show up on slow networks. You must refresh several times to make it work. Or you could try the [v0.3.2](https://github.com/elementdavv/internet_archive_downloader/releases/tag/v0.3.2) that do work on slow networks.

I'm on 0.4.0 by the way

**Comment by elementdavv** [comment]
> I'm on 0.4.0 by the way

buttons not showed up?

**Comment by vehosah** [comment]
> > I'm on 0.4.0 by the way
> 
> v0.4.0 should work well.

But neither the quality button appeared nor the download button appeared, by the way I'm using kiwi browser

**Comment by elementdavv** [comment]
> But neither the quality button appeared nor the download button appeared, by the way I'm using kiwi browser

The extension only support chrome and edge, no wiki.
