### ISSUE TITLE
Microsoft edge 'CRX_REQUIRED_PROOF_MISSING'

### ISSUE THREAD

**Issue by MadShield** [elementdavv/internet_archive_downloader#56]
Hello, I tried to download the downloader for Microsoft edge and when I try to install it by downloading the crx file the message "Package is invalid: 'CRX_REQUIRED_PROOF_MISSING'. I don't know what to do, in all cases thank you for your work and thank you if you fix it. Thanks

**Comment by elementdavv** [comment]
right click and select "save link as ...", and then check the download history that the downloaded file not blocked.

**Comment by Haikel-G** [comment]
> right click and select "save link as ...", and then check the download history that the downloaded file not blocked.

![image](https://github.com/user-attachments/assets/6478b1d3-50d1-4c5c-b075-da802a1c97c1)

**Comment by elementdavv** [comment]
> why I get " Your browser is managed by your organization " ?

It means you have changed the browser security policy.

**Comment by elementdavv** [comment]
> > why I get " Your browser is managed by your organization " ?
> 
> It means you have changed the browser default security policy.
