### ISSUE TITLE
Downloading is blocked.

### ISSUE THREAD

**Issue by Wyddoq** [elementdavv/internet_archive_downloader#58]
It keeps saying "Downloading is blocked. Please contact the developer", on CTRL + "Download" button.

**Comment by Wyddoq** [comment]
I had to downgrade Firefox when I noticed the problem.
Luckily, I made backups.

**Comment by elementdavv** [comment]
> It keeps saying "Downloading is blocked. Please contact the developer", on CTRL + "Download" button.

OK I will look into it.

**Comment by jdeveloperw** [comment]
For anyone on OS X using homebrew who needs to install firefox < 133 to avoid the "Downloading is blocked..." error,  I've confirmed that this extension works for me on OS X with firefox 132.0.2. [This SO post](https://stackoverflow.com/a/66477916/864511) describes how to install homebrew casks at a specific version, and [here is the formula for firefox 132.0.2](https://github.com/Homebrew/homebrew-cask/blob/52d52bee99891db0bc2acc872a7fdaa316642367/Casks/f/firefox.rb) that you'll need to download and install thus:

```bash
brew install --cask ./firefox.rb
```

**Comment by elementdavv** [comment]
Please upgrade to version 1.0.1.
