### ISSUE TITLE
error manifest

### ISSUE THREAD

**Issue by Imanoucat** [elementdavv/internet_archive_downloader#59]
hi i have problem 

Extension failed to load
File
~\OneDrive\Documents\internet_archive_downloader-1.0.1
Error
Manifest file missing or unreadable
Failed to load manifest file.

i use google chrome with the latest update
can you help me ? thanks <3

**Comment by elementdavv** [comment]
internet_archive_downloader-1.0.1.xpi is for Firefox.
You should download [iadownloader-1.0.0.crx](https://github.com/elementdavv/internet_archive_downloader/releases/download/v1.0.0/iadownloader-1.0.0.crx)
