### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Fristender** [elementdavv/internet_archive_downloader#7]
I am using Chrome version 113. When I click download, the progress bar slowly goes up. 30 minutes later(its a long book), the download button says Failed and when I click on it, a message pops up, saying "TypeError: Failed to fetch Please contact developer" or something similar.

**Comment by elementdavv** [comment]
It is because network timeout. Try another time. 
Recently archive.org seems to be not stable. In my case, sometimes download speed gets to several MB/s, sometimes only dozens kB/s.

**Comment by Fristender** [comment]
Yeah, the error seems to happen when the size of the .crswapfile stops increasing.
